### ISSUE TITLE
Parsing NetworkPort

### ISSUE THREAD

**Issue by ahrechushkin** [ManageIQ/manageiq-providers-ovirt#488] opened 2020-03-31 14:31 UTC
I use Ovirt + ManageIQ(Gaprindashvili) + OVN
After refreshing network_ports doen't have - device.
I think problem here:
https://github.com/ManageIQ/manageiq-providers-openstack/blob/master/app/models/manageiq/providers/openstack/inventory/parser/network_manager.rb#L183
In my case i have network_port.device_owner == "oVirt".
Also problem with associations btw Vm and CloudSubnet.

**Comment by gekorob** [comment] 2020-03-31 14:45
@ahrechushkin I'll take a look at it trying to reproduce the problem

**Comment by ahrechushkin** [comment] 2020-04-01 06:56
@gekorob 
I tried to fix it, but have one problem, guest device doesn't have ems_ref attribute which used in lazy_find.
https://github.com/ManageIQ/manageiq-providers-ovirt/pull/490/files

If you'll need some logs or tests you can ping me here or in gitter

**Comment by gekorob** [comment] 2020-04-01 07:00
@ahrechushkin I'll try to reproduce the problem on master and for sure I'll ping you for more information.
Thanks for your availability

**Comment by ahrechushkin** [comment] 2020-04-01 07:20
@gekorob if you have more free time could you please check in G-ver :)

**Comment by gtanzillo** [comment] 2020-04-02 17:34
@gekorob  Does the PR above fix this issue? Can it be closed?

**Comment by gekorob** [comment] 2020-04-02 17:50
@gtanzillo the problem is fixed on master and I don't think we'll have time to work on Gaprindashvili for now (it's too old indeed), so I'm closing the issue

**Closed by gekorob** 2020-04-02 17:50 UTC
