### ISSUE TITLE
VM Platform not discovered for Oracle Linux OS

### ISSUE THREAD

**Issue by szajac01** [ManageIQ/manageiq-providers-ovirt#683] opened 2024-11-25 17:38 UTC
VM platform and guest_os is not discovered properly.
Think it's [here ](https://github.com/ManageIQ/manageiq-providers-ovirt/blob/master/app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb#L607)

All Oracle Linux VM on my OLVM Platform (discovered with RedHat virtualization provider) shows an unknown platform in ManageIQ

`irb(main):002:0> vm_name = "my-ol8_template"`
`irb(main):003:0> vm = $evm.vmdb(:vm_or_template).find_by(name: vm_name)`
`irb(main):004:0> puts vm.platform`
`unknown`

Also another difference with the same vm discovered on a VMWare provider, guest_ois is discovered as ol_8x64, in VMware it's discovered as oraclelinux

Ovirt
![image](https://github.com/user-attachments/assets/1bf1fd3f-b4a7-4d35-bdb2-37c8f9f05406)
VMWare
![image](https://github.com/user-attachments/assets/a8637999-b30a-42e3-9609-aee5d64cd7f2)

It's on petrosian-1.20230912222549_a07cb46
There are several impacts: major is that standard provisioning workflow fails as it's trying to execute a pre_unknown step...

There are no others OS type on this platform to tell you if it's only Oracle Linux that is not properly discovered...

**Comment by szajac01** [comment] 2024-11-27 12:59
hi guys, don't know if it's really a bug
 Based on infra_manager:rb that retrieves #<OvirtSDK4::Template> object, information seems to be correctly retrieved from OLVM.
There are no more information regarding VM type.
vm.os.type is ol_8x64 and vm.os.version is blank

We have to post process this in a workflow to determine platform.

Not sure it's a bug so...

**Comment by Fryguy** [comment] 2024-11-27 14:35
If we have ol_8x64 coming back, then we can post process that to show the correct OS.  @nasark can you take a look at this one?

**Comment by nasark** [comment] 2024-11-28 18:08
I dont have access to an ovirt/rhv env at the moment, @szajac01 can you provide what is being returned by the API in the ` #OvirtSDK4::Template` object? This will help to debug why the platform is persisted as `unknown`

> Also another difference with the same vm discovered on a VMWare provider, guest_ois is discovered as ol_8x64, in VMware it's discovered as oraclelinux

This is just a matter of what is being returned by ovirt vs. vmware, they are both referring to the same thing which is oracle linux

**Comment by szajac01** [comment] 2024-11-29 10:47
Hello, here are the datas
[Uploading OvirtSDK4Template.txt…]()

**Comment by szajac01** [comment] 2024-11-29 10:48
Here are the datas
[OvirtSDK4Template.txt](https://github.com/user-attachments/files/17958079/OvirtSDK4Template.txt)

**Comment by Fryguy** [comment] 2024-12-02 15:05
@nasark Just for clarity - this example that was posted has `ol_9x64`, as opposed to `ol_8x64`, but we should probably support both.

**Comment by nasark** [comment] 2024-12-02 20:37
The response posted seems fine to me, here is where the response is parsed for the OS on VMs https://github.com/ManageIQ/manageiq-providers-ovirt/blob/petrosian/app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb#L463

@szajac01 if a debugger can be placed there we should be able to see what is going wrong

Other points of interest:
- https://github.com/ManageIQ/manageiq-providers-ovirt/blob/petrosian/app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb#L608-L611
- we could also see if host OS is parsed correctly https://github.com/ManageIQ/manageiq-providers-ovirt/blob/petrosian/app/models/manageiq/providers/ovirt/inventory/parser/infra_manager.rb#L368

**Comment by Fryguy** [comment] 2024-12-02 21:06
@nasark I think the problem is not the parser side (since we see the value in the UI - I think the problem is on the normalization side here: https://github.com/ManageIQ/manageiq/blob/master/app/models/operating_system.rb#L13, and that it's not recognized as an OS pattern.

**Comment by Fryguy** [comment] 2024-12-04 20:22
Fixed in #23290

**Closed by Fryguy** 2024-12-04 20:22 UTC
Labels: bug
