### ISSUE TITLE
Adding new Ovirt Provider Validate Button is Greyed out after Adding Credentials

### ISSUE THREAD

**Issue by jerryk55** [ManageIQ/manageiq-providers-ovirt#522] opened 2020-09-10 18:06 UTC
<img width="1335" alt="Screen Shot 2020-09-10 at 1 12 31 PM" src="https://user-images.githubusercontent.com/6118503/92777812-903b9f00-f36e-11ea-8972-3f3b1216949e.png">

After adding the credentials the Validate button is still greyed out but the "Validation Required" message still appears so one is unable to add a new Ovirt provider.

@skateman this is for you to look at.  Thanks.

**Comment by jerryk55** [comment] 2020-09-11 20:27
By the way - this has been validated against the Chrome, Firefox, and Brave browsers.  All have the same issue.

**Comment by skateman** [comment] 2020-09-12 05:40
@jerryk55 the issue is global and related to the provider form, not just the oVirt. I was thinking about the right solution most of yestterday and even pinged MartinM about it. If you really need this feature right now, I can make you a temporary workaround...

**Comment by skateman** [comment] 2020-09-17 06:41
Tests are green on the fix, waiting for someone to merge it...

**Comment by skateman** [comment] 2020-09-21 14:08
@miq-bot close_issue
Resolved via https://github.com/ManageIQ/manageiq-ui-classic/pull/7308

**Closed** 2020-09-21 14:09 UTC
Labels: bug
